# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f33e1bfcce8fe6f0e65fcce2538338abb4a80be3c7b285fefa236f545582452eef03f5eeb41f5126599f89fdd4c23aa70f8aa5f9cf73bffd6ebc73873fe92dd

test:
  secret_key_base: bf3a08cd1344f978e1480fa5500011eb15219ffaae0010e32ff62ff1946a1fadd9a82eebd53beef9f28aeb42bc0f7ebe59b75470a9c45e3c5c5b5d54fbbf6199

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
